# Generated by Django 2.1.1 on 2018-09-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(blank=True, max_length=100)),
                ('header_image_1600x660', models.ImageField(blank=True, upload_to='')),
                ('image_600x400', models.ImageField(blank=True, upload_to='')),
                ('sub_heading2', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True)),
                ('accordion_title1', models.CharField(blank=True, max_length=100)),
                ('accordion_body1', models.TextField(blank=True)),
                ('accordion_title2', models.CharField(blank=True, max_length=100)),
                ('accordion_body2', models.TextField(blank=True)),
                ('accordion_title3', models.CharField(blank=True, max_length=100)),
                ('accordion_body3', models.TextField(blank=True)),
            ],
        ),
    ]
