# Generated by Django 2.1.1 on 2018-09-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws4thought', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('flaticon-angry-bulldog-face', 'flaticon-angry-bulldog-face'), ('flaticon-animal', 'flaticon-animal'), ('flaticon-animal-1', 'flaticon-animal-1'), ('flaticon-animal-2', 'flaticon-animal-2'), ('.flaticon-animal-3', '.flaticon-animal-3'), ('flaticon-animal-4', 'flaticon-animal-4'), ('flaticon-animal-5', 'flaticon-animal-5'), ('flaticon-animal-6', 'flaticon-animal-6'), ('flaticon-animal-7', 'flaticon-animal-7'), ('flaticon-animal-8', 'flaticon-animal-8'), ('flaticon-animal-paw-print', 'flaticon-animal-paw-print'), ('flaticon-animals', 'flaticon-animals'), ('flaticon-animals-1', 'flaticon-animals-1'), ('flaticon-animals-2', 'flaticon-animals-2'), ('flaticon-animals-3', 'flaticon-animals-3'), ('flaticon-animals-4', 'flaticon-animals-4'), ('flaticon-animals-5', 'flaticon-animals-5'), ('flaticon-animals-6', 'flaticon-animals-6'), ('flaticon-animals-7', 'flaticon-animals-7'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], default='None', max_length=50)),
            ],
        ),
    ]
