# Generated by Django 2.1.1 on 2018-09-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws4thought', '0005_about_body2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Company',
        ),
    ]
