# Generated by Django 2.1.1 on 2018-09-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws4thought', '0006_auto_20180915_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
