# Generated by Django 2.1.1 on 2018-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws4thought', '0008_company_home_page_image_800x1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('image_350x350', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
