# Generated by Django 2.1.1 on 2018-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws4thought', '0010_auto_20180916_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=100)),
                ('sub_heading', models.CharField(blank=True, max_length=100)),
                ('header_image_1600x660', models.ImageField(blank=True, upload_to='')),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
