# Generated by Django 2.1.1 on 2018-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws4thought', '0013_auto_20180916_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('image_1600x900', models.ImageField(blank=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
