# Generated by Django 2.1.1 on 2018-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws4thought', '0014_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
