# Generated by Django 2.1.1 on 2018-09-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180915_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='header_image',
            new_name='image',
        ),
    ]
