# Generated by Django 2.1.1 on 2018-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180915_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=100)),
                ('header_image_1600x660', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_800x800',
        ),
    ]
