# Generated by Django 2.1.1 on 2018-09-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20180916_0945'),
        ('gallery', '0005_auto_20180916_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
    ]
