# Generated by Django 2.1.1 on 2018-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='image_500x600_homepage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
