# Generated by Django 2.1.1 on 2018-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='bullets1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='bullets9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
