# Generated by Django 2.1.1 on 2018-09-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180915_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Overview',
        ),
    ]
