# Generated by Django 2.1.1 on 2018-09-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_bullet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='intro_bold_text',
            field=models.TextField(blank=True),
        ),
    ]
