# Generated by Django 2.1.1 on 2018-09-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20180915_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bullets10_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets1_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets2_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets3_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets4_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets5_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets6_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets7_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets8_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets9_body',
            field=models.TextField(blank=True),
        ),
    ]
