# Generated by Django 2.1.1 on 2018-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20180915_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='header_image_1600x660',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
