# Generated by Django 2.1.1 on 2018-09-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_overview_header_image_1600x660'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Overview',
            new_name='ServicesPage',
        ),
    ]
