# Generated by Django 2.1.1 on 2018-09-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20180916_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesPage',
            new_name='ServicesDetail',
        ),
    ]
