# Generated by Django 2.1.1 on 2018-09-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0016_auto_20180916_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True)),
                ('image_100x100', models.ImageField(blank=True, upload_to='')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('header_image_1600x660', models.ImageField(blank=True, upload_to='')),
                ('image_690x500', models.ImageField(blank=True, upload_to='')),
                ('body', models.TextField(blank=True)),
                ('body2', models.TextField(blank=True)),
            ],
        ),
    ]
